### ISSUE TITLE
configurar alert_rules em todos níveis 

### ISSUE THREAD

**Issue by elisvaldoazevedo** [labbsr0x/bb-promster#2]
Em todos níveis deveriamos ter a liberdade de configurar regras de alertas e endereço do alertmanager.

**Comment by eabili0** [comment]
@elisvaldoazevedo, isso foi revisado para permitir regras de alertas apenas no nível 1. Regras de alerta em outros níveis precisam ser evitadas para não limitar a possibilidade de alertas duplicados. 

Caso esteja usando com cortex, as regras de alertas precisam estar desabilitadas mesmo em nível 1.
