### ISSUE TITLE
Proposal for bb-promster

### ISSUE THREAD

**Issue by gutorc92** [labbsr0x/bb-promster#28]
Bb-promster is being used in production for a while. Before bb-promster, scrape targets were set statically on building run-time. bb-promster introduces an ETCD database to manage all IPs that Prometheus needs to monitor, speeding up the targets update process.
However, it has some issues to update some attributes that belong to a target. Currently, bb-promster only watch changes on IPs, but on real monitoring, it's also necessary to keep tracking of scrape path, relabel_configs, and SSL certificate. It could be interesting to allow bb-promster to watch changes on other attributes, so the need to modify the deploy will be minimum.
Considering that, we propose bb-promster not watch just IPs, but a complete app object as bb-bot does.

![Blank Diagram](https://user-images.githubusercontent.com/2671806/87707037-db727080-c776-11ea-9274-a384df0a6655.png)

App structure will be responsible for keeping data related to a context being monitored, attributes like name, scrapePath, and so on. App also has an internal struct called Env to manage contexts with blue/green deployment. 
Settings is an auxiliary structure to keep data related to all bb-promster, as the remote write URL and etcd service where apps are saved.
It is an initial proposal that can also include the bb-promsters status or pod names in order to centralize information for operation teams.

Thanks to @KarineValenca for helping me with the text.

**Comment by eabili0** [comment]
@gutorc92, first and foremost, thank you for opening this up for discussion!

It seems reasonable to me, but I think it would be wise to put @flaviostutz on this discussion as well, since we would be moving away from the initial design proposed by [Promster](https://github.com/flaviostutz/promster);

While we wait for @flaviostutz's input, could you please rewrite your proposal to remove k8s terms, such as `namespaces` and `pods`?  Our design should always be tech free.

Other questions:

1. It is easy today to leverage operations on ETCD keys' prefixes. For example, if I need a list of IPs of an App, I just do `GET /services/app-name`. If my app is made of many subapps, I can just prefix `app-name` with `something` else and use that `something` to GET all my app's IPs: `GET /services/something-`. How do you plan to have the same flexibility and speed? 

2. Are you maybe aiming to lose some flexibility and speed on generic operations to make the operations **you** use more optimal? If so, could you please specify the use cases? We need to understand if your proposal should be a new fork of Promster or should indeed be absorbed  by BB Promster.

**Comment by flaviostutz** [comment]
I didn't go into depth on this, but what if we use the custom parameters as part of the node name in etcd registration?

So ETCD tree would be something like
    /services/myapp
           - "192.168.5.66:8088/metrics[relabel1]" (instead of "192.168.5.66")
           - "192.168.5.65:8088/metrics"
           - "192.168.5.62:8088/metrics"

In this case, when registrar 192.168.5.66 changes its parameters, a new node "192.168.5.66:8088/metrics2[relabel2]" would be created (by the client registrar) - the last one will be expired - and Promster will use the newer parameters.

This way only the registrar would be changed, keeping the good use of ETCD features for change detection.

Would this solve your problem?

**Comment by gutorc92** [comment]
> @gutorc92, first and foremost, thank you for opening this up for discussion!
> 
> It seems reasonable to me, but I think it would be wise to put @flaviostutz on this discussion as well, since we would be moving away from the initial design proposed by [Promster](https://github.com/flaviostutz/promster);
> 
> While we wait for @flaviostutz's input, could you please rewrite your proposal to remove k8s terms, such as `namespaces` and `pods`? Our design should always be tech free.
> 
> Other questions:
> 
> 1. It is easy today to leverage operations on ETCD keys' prefixes. For example, if I need a list of IPs of an App, I just do `GET /services/app-name`. If my app is made of many subapps, I can just prefix `app-name` with `something` else and use that `something` to GET all my app's IPs: `GET /services/something-`. How do you plan to have the same flexibility and speed?


 Some Apps have more than 30 IPs on etcd, the etcdctl tool does not have commands to count by a prefix so it is not possible to check if all targets are registred. Also, check one by one is error prune. Then, Bb-bot api can implements more operations tasks such as list IPs for an app, add new IPs, and so on.  

> 2. Are you maybe aiming to lose some flexibility and speed on generic operations to make the operations **you** use more optimal? If so, could you please specify the use cases? We need to understand if your proposal should be a new fork of Promster or should indeed be absorbed  by BB Promster.

The operation I use more is update the targets on ETCD. To do it, I need to know which targets are no longer used and add new ones. The new data came as csv files that need to be check one by one if they should be on ETCD. BB-bot can implement some endpoint to do it. BB-bot api also has the advantage to has a front-end what can improve operations tasks.

**Comment by gutorc92** [comment]
> I didn't go into depth on this, but what if we use the custom parameters as part of the node name in etcd registration?
> 
> So ETCD tree would be something like
> /services/myapp
> - "192.168.5.66:8088/metrics[relabel1]" (instead of "192.168.5.66")
> - "192.168.5.65:8088/metrics"
> - "192.168.5.62:8088/metrics"
> 
> In this case, when registrar 192.168.5.66 changes its parameters, a new node "192.168.5.66:8088/metrics2[relabel2]" would be created (by the client registrar) - the last one will be expired - and Promster will use the newer parameters.
> 
> This way only the registrar would be changed, keeping the good use of ETCD features for change detection.
> 
> Would this solve your problem?

@flaviostutz, I have done some tests and I come with this proposal after test if update some nested property of App such Env will trigger the watch method of ETCD lib.  I had worked on some tests in this branch: https://github.com/gutorc92/promster/tree/prometheus_config2

**Comment by eabili0** [comment]
@gutorc92, sorry, didn't understand.

Have you tested if changes to nested info on an ETCD node triggers the registry watch method? Does it work?

**Comment by gutorc92** [comment]
> @gutorc92, sorry, didn't understand.
> 
> Have you tested if changes to nested info on an ETCD node triggers the registry watch method? Does it work?

That's what I mean. 

You can test it, using this docker-compose:

```
version: '3.5'

services:
  bot:
    image: gutorc92/bb-bot:teste
    environment:
      - ETCD_URLS=http://etcd:2379
      - TELEGRAM_TOKEN=<your telegram token>
      - DEBUG=*
      - LANGUAGE=en
      - BASIC_AUTH_USERNAME=bot
      - BASIC_AUTH_PASSWORD=bot
    ports:
      - 3000:3000
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  example-service:
    image: abilioesteves/metrics-generator
    depends_on:
      - etcd
    ports:
      - 32865
    environment:
      - REGISTRY_ETCD_BASE=/webpj35
      - REGISTRY_SERVICE=exemple-1
      - REGISTRY_ETCD_URL=http://etcd:2379
  
  example-bb-promster:
    image: gutorc92/promster:latest
    depends_on:
      - etcd
      - example-service
    ports:
      - 9091:9090
    environment:
      - LOG_LEVEL=debug
      - REGISTRY_ETCD_URL=http://etcd:2379
      - REGISTRY_SERVICE=exemple-1-promster
      - REGISTRY_ETCD_BASE=/services
      - BB_PROMSTER_LEVEL=1
      - ETCD_URLS=http://etcd:2379
      - SCRAPE_ETCD_PATH=/apps/webpj35-exemple-1
      - SCRAPE_ETCD_URL=http://etcd:2379
      - SCRAPE_SHARD_ENABLE=false
      # - REMOTE_WRITE_URL=http://34.67.146.19/api/prom/push
```

1. migrate app to the new structure using url: ```/migration```.
2. Change some of ```webpj35-exemple-1``` attributes. 

You should see on promster logs the new prometheus.yaml file been generated.

If you use postman, you can import requests 1 and 2 using this files:
 
[Bot_b5.postman_collection.json.zip](https://github.com/labbsr0x/bb-promster/files/4949560/Bot_b5.postman_collection.json.zip)

**Comment by eabili0** [comment]
> This way only the registrar would be changed, keeping the good use of ETCD features for change detection.

@flaviostutz, apparently ETCD is also able to detect changes to the entries' values, instead of only entries' keys. Is this still considered bad usage of such feature? If so, could you please explain why?
