### ISSUE TITLE
bb-promster container breaks after restarting when there's /versions registered

### ISSUE THREAD

**Issue by KarineValenca** [labbsr0x/bb-promster#30]
After a container/pod restart, when there's /versions registered in ETCD, the bb-promster container breaks. 
The problem happens due to the main.go file, that takes care of updating alert rules files. It needs further investigation to find out why the problem is happening.

**Comment by eabili0** [comment]
Thank you for letting us know, @KarineValenca! I've assigned this issue for you to take care of. Please let me know if I can help you with anything!
